# 1. Load the Packages

In [3]:
import warnings
warnings.filterwarnings("ignore", category=FutureWarning)

import pandas as pd
import numpy as np
from datetime import datetime, date, timedelta
from sklearn.linear_model import LogisticRegression
from sklearn import metrics

# Shows plots in jupyter notebook
%matplotlib inline

# Set plot style
sns.set(color_codes=True)

# 2. Load the dataset (set the directory)

In [9]:
# Set the working directory to the location of the data file
import os 
os.chdir('/Users/surajgurung/Library/CloudStorage/OneDrive-UniversityofFlorida/AI&FINtech/JPMorgan_Simulation')

# Load the data set
df = pd.read_csv('Loan_Data.csv')

df.columns
df.dtypes
df.head(5)

,customer_id,credit_lines_outstanding,loan_amt_outstanding,total_debt_outstanding,income,years_employed,fico_score,default
0,8153374,0,5221.545193,3915.471226,78039.38546,5,605,0
1,7442532,5,1958.928726,8228.752520,26648.43525,2,572,1
2,2256073,0,3363.009259,2027.830850,65866.71246,4,602,0
3,4885975,0,4766.648001,2501.730397,74356.88347,5,612,0
4,4700614,1,1345.827718,1768.826187,23448.32631,6,631,0

# 3. Define the input 
- These are the X- variables

In [10]:
features = ['credit_lines_outstanding', 'debt_to_income', 'payment_to_income', 'years_employed', 'fico_score']

# 4. Create payment-to-income ratio

In [12]:
df['payment_to_income'] = df['loan_amt_outstanding']/df['income']
df.head(5)

,customer_id,credit_lines_outstanding,loan_amt_outstanding,total_debt_outstanding,income,years_employed,fico_score,default,payment_to_income
0,8153374,0,5221.545193,3915.471226,78039.38546,5,605,0,0.066909
1,7442532,5,1958.928726,8228.752520,26648.43525,2,572,1,0.073510
2,2256073,0,3363.009259,2027.830850,65866.71246,4,602,0,0.051058
3,4885975,0,4766.648001,2501.730397,74356.88347,5,612,0,0.064105
4,4700614,1,1345.827718,1768.826187,23448.32631,6,631,0,0.057395

# 5. Create debt-to-income ratio

In [13]:
df['debt_to_income'] = df['total_debt_outstanding'] / df['income']

# 6. Fit the logistic regression model

In [ ]:
clf = LogisticRegression(random_state=0, solver='liblinear', tol=1e-5, max_iter=10000).fit(df[features], df['default'])
# Print coefficients and intercept
print(clf.coef_, clf.intercept_)

[[ 8.18520373  0.54490854  0.01994244 -2.77630853 -0.02418391]] [-0.09162643]

# 7. Predict default class

In [18]:
y_pred = clf.predict(df[features])
y_pred

array([0, 1, 0, ..., 0, 0, 0])

# 8. Compute the ROC curve

In [ ]:
fpr, tpr, thresholds = metrics.roc_curve(df['default'], y_pred)

0.0037
0.9925106069101026